version: "3.8"
services:
  goapp: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    container_name: QUESTIONS150
    stdin_open: true # 標準入出力とエラー出力をコンテナdockeに結びつける設定
    tty: true # コンテナの永続化
    ports:
      - 2347:2347 # delve(debug)用
    volumes:
      - ./src:/src # マウントディレクトリ
